package net.ahmed.app.dal.entity;
// Generated Sep 5, 2020 12:30:41 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

/**
 * Content generated by hbm2java
 */
@Entity(name = "content")
public class Content implements java.io.Serializable {

    private Integer id;
    private CourseOutlines topic;
    private String title;
    private String video;
    private String duration;
    private Integer period;
    private String description;
    private int CourseId;
    private String topicId;
    private MultipartFile lessonVideo;
    private Date uploadDate;
    private String extension;

    public Content() {
    }

    public Content(CourseOutlines topic, String title, Integer period, Date uploadDate) {
        this.topic = topic;
        this.title = title;
        this.period = period;
        this.uploadDate = uploadDate;
    }

    public Content(CourseOutlines topic, String title, Integer period, String description, Date uploadDate) {
        this.topic = topic;
        this.title = title;
        this.period = period;
        this.description = description;
        this.uploadDate = uploadDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "outline_id", nullable = false)
    public CourseOutlines getTopic() {
        return this.topic;
    }

    public void setTopic(CourseOutlines topic) {
        this.topic = topic;
    }

    @Column(name = "title", nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "period")
    public Integer getPeriod() {
        return this.period;
    }

    public void setPeriod(Integer period) {
        this.period = period;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Column(name = "upload_date", nullable = false, length = 10)
    public Date getUploadDate() {
        return this.uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    @Column(name = "video")
    public String getVideo() {
        return video;
    }

    public void setVideo(String video) {
        this.video = video;
    }
    
    @Transient
    public int getCourseId() {
        return CourseId;
    }

    public void setCourseId(int CourseId) {
        this.CourseId = CourseId;
    }
    
    @Transient
    public MultipartFile getLessonVideo() {
        return lessonVideo;
    }

    public void setLessonVideo(MultipartFile lessonVideo) {
        this.lessonVideo = lessonVideo;
    }
    @Transient
    public String getTopicId() {
        return topicId;
    }

    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }
    @Transient
    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }
    @Transient
    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }
    
    
}
