package net.ahmed.app.dal.entity;
// Generated Sep 5, 2020 12:30:41 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Content generated by hbm2java
 */
@Entity(name = "content")
public class Content implements java.io.Serializable {

    private Integer id;
    private Course course;
    private CourseOutlines courseOutlines;
    private String title;
    private Date period;
    private String description;
    private Date uploadDate;

    public Content() {
    }

    public Content(Course course, CourseOutlines courseOutlines, String title, Date period, Date uploadDate) {
        this.course = course;
        this.courseOutlines = courseOutlines;
        this.title = title;
        this.period = period;
        this.uploadDate = uploadDate;
    }

    public Content(Course course, CourseOutlines courseOutlines, String title, Date period, String description, Date uploadDate) {
        this.course = course;
        this.courseOutlines = courseOutlines;
        this.title = title;
        this.period = period;
        this.description = description;
        this.uploadDate = uploadDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "outline_id", nullable = false)
    public CourseOutlines getCourseOutlines() {
        return this.courseOutlines;
    }

    public void setCourseOutlines(CourseOutlines courseOutlines) {
        this.courseOutlines = courseOutlines;
    }

    @Column(name = "title", nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "period", nullable = false, length = 8)
    public Date getPeriod() {
        return this.period;
    }

    public void setPeriod(Date period) {
        this.period = period;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Column(name = "start_date", nullable = false, length = 10)
    public Date getUploadDate() {
        return this.uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

}
