package net.ahmed.app.dal.entity;
// Generated Jul 16, 2020 12:45:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InstructorField generated by hbm2java
 */
@Entity
@Table(name="instructor_field"
    ,catalog="online_courses_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class InstructorField  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Instructor> instructors = new HashSet<Instructor>(0);

    public InstructorField() {
    }

	
    public InstructorField(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public InstructorField(int id, String name, Set<Instructor> instructors) {
       this.id = id;
       this.name = name;
       this.instructors = instructors;
    }

    public InstructorField(String name) {
        this.name = name;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instructorField")
    public Set<Instructor> getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set<Instructor> instructors) {
        this.instructors = instructors;
    }




}


