package net.ahmed.app.dal.entity;
// Generated Jul 16, 2020 12:45:46 AM by Hibernate Tools 4.3.1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

/**
 * Instructor generated by hbm2java
 */
@Entity
@Table(name = "instructor", catalog = "online_courses_db")
public class Instructor implements java.io.Serializable {

	private Integer id;
	private InstructorField instructorField;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String confrimPassword;
	private MultipartFile profileImage;
	private MultipartFile userCV;
	private String cvFile;
	private String photo;
	private Integer yearOfExp;
	private Date birthDate;
	private String country;
	private String gender;
	private String description;
	private Set<Course> courses = new HashSet<Course>(0);

	public Instructor() {
	}

	public Instructor(Integer id, InstructorField instructorField, String firstName, String lastName, String email,
			String password, String cvFile, String photo, Integer yearOfExp, Date birthDate) {
		this.id = id;
		this.instructorField = instructorField;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.cvFile = cvFile;
		this.photo = photo;
		this.yearOfExp = yearOfExp;
		this.birthDate = birthDate;
	}

	public Instructor(Integer id, InstructorField instructorField, String firstName, String lastName, String email,
			String password, String cvFile, String photo, Integer yearOfExp, Date birthDate, String country,
			Set<Course> courses) {
		this.id = id;
		this.instructorField = instructorField;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.cvFile = cvFile;
		this.photo = photo;
		this.yearOfExp = yearOfExp;
		this.birthDate = birthDate;
		this.country = country;
		this.courses = courses;
	}

	public Instructor(String firstName, String lastName, String email, String password, String cvFile, String photo,
			Integer yearOfExp, Date birthDate, String country) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.cvFile = cvFile;
		this.photo = photo;
		this.yearOfExp = yearOfExp;
		this.birthDate = birthDate;
		this.country = country;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.MERGE)
	@JoinColumn(name = "field", nullable = false)
	public InstructorField getInstructorField() {
		return this.instructorField;
	}

	public void setInstructorField(InstructorField instructorField) {
		this.instructorField = instructorField;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Transient
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Transient
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cv_file", nullable = false)
	public String getCvFile() {
		return this.cvFile;
	}

	public void setCvFile(String cvFile) {
		this.cvFile = cvFile;
	}

	@Column(name = "photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "yearOfExp", nullable = false)
	public Integer getYearOfExp() {
		return this.yearOfExp;
	}

	public void setYearOfExp(Integer yearOfExp) {
		this.yearOfExp = yearOfExp;
	}
	
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Column(name = "birth_date", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instructor")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	@Column(name = "gender")
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Transient
	public String getConfrimPassword() {
		return confrimPassword;
	}

	public void setConfrimPassword(String confrimPassword) {
		this.confrimPassword = confrimPassword;
	}
	@Transient
	public MultipartFile getProfileImage() {
		return profileImage;
	}

	public void setProfileImage(MultipartFile profileImage) {
		this.profileImage = profileImage;
	}
	@Transient
	public MultipartFile getUserCV() {
		return userCV;
	}

	public void setUserCV(MultipartFile userCV) {
		this.userCV = userCV;
	}
	
}
