package net.ahmed.app.dal.entity;
// Generated Jul 16, 2020 12:45:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Instructor generated by hbm2java
 */
@Entity
@Table(name="instructor"
    ,catalog="online_courses_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Instructor  implements java.io.Serializable {


     private int id;
     private InstructorField instructorField;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private String cvFile;
     private String photo;
     private int yearOfExp;
     private Date birthDate;
     private String country;
     private Set<Course> courses = new HashSet<Course>(0);

    public Instructor() {
    }

	
    public Instructor(int id, InstructorField instructorField, String firstName, String lastName, String email, String password, String cvFile, String photo, int yearOfExp, Date birthDate) {
        this.id = id;
        this.instructorField = instructorField;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.cvFile = cvFile;
        this.photo = photo;
        this.yearOfExp = yearOfExp;
        this.birthDate = birthDate;
    }
    public Instructor(int id, InstructorField instructorField, String firstName, String lastName, String email, String password, String cvFile, String photo, int yearOfExp, Date birthDate, String country, Set<Course> courses) {
       this.id = id;
       this.instructorField = instructorField;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.cvFile = cvFile;
       this.photo = photo;
       this.yearOfExp = yearOfExp;
       this.birthDate = birthDate;
       this.country = country;
       this.courses = courses;
    }

    public Instructor(String firstName, String lastName, String email, String password, String cvFile, String photo, int yearOfExp, Date birthDate, String country) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.cvFile = cvFile;
        this.photo = photo;
        this.yearOfExp = yearOfExp;
        this.birthDate = birthDate;
        this.country = country;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="field", nullable=false)
    public InstructorField getInstructorField() {
        return this.instructorField;
    }
    
    public void setInstructorField(InstructorField instructorField) {
        this.instructorField = instructorField;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="cv_file", nullable=false)
    public String getCvFile() {
        return this.cvFile;
    }
    
    public void setCvFile(String cvFile) {
        this.cvFile = cvFile;
    }

    
    @Column(name="photo", nullable=false)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="yearOfExp", nullable=false)
    public int getYearOfExp() {
        return this.yearOfExp;
    }
    
    public void setYearOfExp(int yearOfExp) {
        this.yearOfExp = yearOfExp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", nullable=false, length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="Country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instructor")
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


